name: Run Tests

on:
  push:
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]
    
    name: P${{ matrix.php }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
      
      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "highest"
          composer-options: "--prefer-dist --no-interaction --no-suggest"
      
      - name: Execute tests
        run: vendor/bin/phpunit
